version: 2

run:
  timeout: 60m
  test: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# v2 replacement for "issues.exclude-rules"
rules:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019: .* is deprecated"

    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec
        - dupl

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - unconvert
    - staticcheck
    - errcheck
    - ineffassign
    - unused

lintersSettings:
  errcheck:
    exclude-functions:
      - (github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
      - (github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).SetId
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).SetId
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln

  govet:
    settings:
      printf:
        funcs:
          - diag.Errorf
          - diag.Warningf

  nakedret:
    max-func-lines: 40
